global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fabric-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway:3100']
    scrape_interval: 10s
